import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Raleway, Inter } from "next/font/google";
// import Footer from "@/components/Footer";
import LayoutWithFooter from "@/components/LayoutWithFooter";

const satoshiFont = localFont({
  src: "./fonts/Satoshi-Regular.otf", // You can use the .otf format here
  variable: "--font-satoshi",
  weight: "400",
});
const satoshiFontBold = localFont({
  src: "./fonts/Satoshi-Bold.otf", // You can use the .otf format here
  variable: "--font-satoshibold",
  weight: "700",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const secondaryFont = Raleway({
  subsets: ["latin"],
  variable: "--font-raleway",
  display: "swap",
  adjustFontFallback: false,
});
const secondaryFont2 = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
  adjustFontFallback: false,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${satoshiFont.variable} ${satoshiFontBold.variable} ${geistMono.variable} ${secondaryFont.variable} ${secondaryFont2.variable} antialiased no-scrollbar bg-[#F8F8F8]`}
      >
        {" "}
        <main className="no-scrollbar min-h-screen w-full overflow-x-hidden">
          {/* {children} */}
          <LayoutWithFooter>{children}</LayoutWithFooter>
        </main>
      </body>
    </html>
  );
}
